apiVersion: travis.operator.com/v1
kind: AppService
metadata:
  name: example-appservice
spec:
  # Add fields here
  size: 3
  image: nginx:alpine
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30086

